import { ThemeConfig } from "@/types/calendar";

export const monthThemes: Record<number, ThemeConfig> = {
  0: {
    name: "January",
    image: "/images/jjan.jpg",
    primary: "#2563EB",
    accent: "#93C5FD",
    bg: "#F8FAFC",
    text: "#0F172A",
  },
  1: {
    name: "February",
    image: "/images/feb.png",
    primary: "#EC4899",
    accent: "#F9A8D4",
    bg: "#FFF1F2",
    text: "#4C0519",
  },
  2: {
    name: "March",
    image: "/images/mar.png",
    primary: "#22C55E",
    accent: "#86EFAC",
    bg: "#F0FDF4",
    text: "#052E16",
  },
  3: {
    name: "April",
    image: "/images/apr.png",
    primary: "#F472B6",
    accent: "#FBCFE8",
    bg: "#FDF2F8",
    text: "#831843",
  },
  4: {
    name: "May",
    image: "/images/may.png",
    primary: "#EAB308",
    accent: "#FDE047",
    bg: "#FEFCE8",
    text: "#422006",
  },
  5: {
    name: "June",
    image: "/images/jun.png",
    primary: "#06B6D4",
    accent: "#67E8F9",
    bg: "#ECFEFF",
    text: "#083344",
  },
  6: {
    name: "July",
    image: "/images/jul.png",
    primary: "#F97316",
    accent: "#FDBA74",
    bg: "#FFF7ED",
    text: "#431407",
  },
  7: {
    name: "August",
    image: "/images/aug.png",
    primary: "#16A34A",
    accent: "#4ADE80",
    bg: "#F0FDF4",
    text: "#022C22",
  },
  8: {
    name: "September",
    image: "/images/sep.png",
    primary: "#D97706",
    accent: "#FBBF24",
    bg: "#FFFBEB",
    text: "#451A03",
  },
  9: {
    name: "October",
    image: "/images/oct.png",
    primary: "#EA580C",
    accent: "#FDBA74",
    bg: "#FFF7ED",
    text: "#1C1917",
  },
  10: {
    name: "November",
    image: "/images/nov.png",
    primary: "#F59E0B",
    accent: "#FCD34D",
    bg: "#FFFBEB",
    text: "#78350F",
  },
  11: {
    name: "December",
    image: "/images/dec.png",
    primary: "#DC2626",
    accent: "#FCA5A5",
    bg: "#FEF2F2",
    text: "#450A0A",
  },
};